### ISSUE TITLE
Staff suggestioin 329

### ISSUE THREAD

**Issue by MrFluffy-BTE** [BuildTheEarth/main-bot#145] opened 2021-03-23 14:49 UTC
#329:
Team: Bot Dev
Suggestion: some sort of .toLowerCase() for when the bot figures out what you put in the snippet name argument for the snippet related commands.
Reason: It is annoying to have to remember the exact capitalization of snippets with longer names, and then having to keep referring back to the list. For example, rn, only !s WorldNotFound works. Beforehand i tried !s worldnotfound, !s worldNotFound before i finally went back to the list. Its not that big of a deal, just would make ticket people's jobs a little easier :upside_down:

From: MrSmarty#1732

**Comment by XboxBedrock** [comment] 2021-03-23 16:12
You opened an issue on the wrong repo, this belongs on the support bot repo.

**Comment by cAttte** [comment] 2021-03-23 16:24
duplicate of BuildTheEarth/support-bot#2

**Closed by cAttte** 2021-03-23 16:24 UTC
